server:
  port: 9090

spring:
  application:
    name: sc-zuul-filter

zuul:
  routes:
    feign:
      path: /feign/**
      serviceId: sc-eureka-client-provider
      
eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl:
      defaultZone: http://localhost:5001/eureka/