eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5001/eureka/
      
server:
  port: 9202
spring:
  application:
    name: sc-zipkin-client-web
  zipkin:
    base-url: http://localhost:9000