server:
  port: 8090
  
jdbc:
  mysql: 
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/userdb?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    driverClassName: com.mysql.jdbc.Driver