server:
  port: 8081
spring:
  application:
    name: cto51-lesson16
  redis: # Redis 配置
    database: 0 # Redis 数据库索引（默认为0）
    host: 127.0.0.1 # Redis 服务器地址
    port: 6379 # Redis 服务器连接端口
    password: # Redis 服务器连接密码（默认为空）
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1
        max-idle: 5
        min-idle: 1
        
 