server:
  port: 8090
  
spring:
  application:
    name: sc-zuul-towway
    
# 路由规则配置
#zuul:
#  routes:
#    user:
#      path: /api/**
#      serviceId: sc-zuul-consumer

#zuul:
#  routes:
#    sc-zuul-consumer:
#      path: /userapi/**
      
# API网关也将作为一个服务注册到eureka-server上
eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl:
      defaultZone: http://localhost:5001/eureka/
      
