server:
  port: 8081
  
spring:
  appliction:
    name: cto51-lesson20
  activiti:
    check-process-definitions: false #不检查流程定义
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update #自动生成activiti的表结构
  show-sql: true #显示SQL语句
