server:
  port: 8081
  
spring:
  appliction:
   name: cto51-lesson18
  activemq:
    in-memory: false
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 50
      expiry-timeout: 10000
      idle-timeout: 30000
  jms: 
    pub-sub-domain: false #默认情况下activemq提供的是queue模式，若要使用topic模式需要配置pub-sub-domain为true