spring:
  application:
    name: sc-eureka-cluster-server-node3
    
server:
  port: 5003
  
eureka:
  instance:
    hostname: sc-eureka-cluster-server-node3
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://sc-eureka-cluster-server-node1:5001/eureka/,http://sc-eureka-cluster-server-node2:5001/eureka/