server:
  port: 8090
  
spring:
  application:
    name: sc-apache-rocketmq
    
rocketmq: 
  # 生产者配置
  producer: 
    groupName: rocketmq-group
    namesrvAddr: 127.0.0.1:9876
    default: false
  # 消费者配置
  consumer: 
    groupName: rocketmq-group
    namesrvAddr: 127.0.0.1:9876